"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import agent_pb2 as _agent_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AgentServiceStub:
    """Agent 智能服务：Java ↔ Python 双向流通信"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AgentServiceAsyncStub: ...
    Chat: _grpc.StreamStreamMultiCallable[_agent_pb2.ClientMessage, _agent_pb2.ServerMessage]
    """双向流 Chat：Java 发送用户消息 / Tool 执行结果，
    Python 返回文本回复 / Tool 调用请求
    """

@_typing.type_check_only
class AgentServiceAsyncStub(AgentServiceStub):
    """Agent 智能服务：Java ↔ Python 双向流通信"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Chat: _aio.StreamStreamMultiCallable[_agent_pb2.ClientMessage, _agent_pb2.ServerMessage]  # type: ignore[assignment]
    """双向流 Chat：Java 发送用户消息 / Tool 执行结果，
    Python 返回文本回复 / Tool 调用请求
    """

class AgentServiceServicer(metaclass=_abc_1.ABCMeta):
    """Agent 智能服务：Java ↔ Python 双向流通信"""

    @_abc_1.abstractmethod
    def Chat(
        self,
        request_iterator: _MaybeAsyncIterator[_agent_pb2.ClientMessage],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_agent_pb2.ServerMessage], _abc.AsyncIterator[_agent_pb2.ServerMessage]]:
        """双向流 Chat：Java 发送用户消息 / Tool 执行结果，
        Python 返回文本回复 / Tool 调用请求
        """

def add_AgentServiceServicer_to_server(servicer: AgentServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
