"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ClientMessage(_message.Message):
    """========== 客户端 → 服务端 =========="""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    USER_MESSAGE_FIELD_NUMBER: _builtins.int
    TOOL_RESULT_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    user_message: _builtins.str
    """用户提问"""
    @_builtins.property
    def tool_result(self) -> Global___ToolResult:
        """Tool 执行结果回传"""

    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        user_message: _builtins.str = ...,
        tool_result: Global___ToolResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "tool_result", b"tool_result", "user_message", b"user_message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "session_id", b"session_id", "tool_result", b"tool_result", "user_message", b"user_message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_content: _TypeAlias = _typing.Literal["user_message", "tool_result"]  # noqa: Y015
    _WhichOneofArgType_content: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_content) -> _WhichOneofReturnType_content | None: ...

Global___ClientMessage: _TypeAlias = ClientMessage  # noqa: Y015

@_typing.final
class ServerMessage(_message.Message):
    """========== 服务端 → 客户端 =========="""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    TOOL_CALL_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    text: _builtins.str
    """最终文本回复"""
    @_builtins.property
    def tool_call(self) -> Global___ToolCall:
        """请求执行 Tool"""

    @_builtins.property
    def error(self) -> Global___Error:
        """错误信息"""

    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        text: _builtins.str = ...,
        tool_call: Global___ToolCall | None = ...,
        error: Global___Error | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "error", b"error", "text", b"text", "tool_call", b"tool_call"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "error", b"error", "session_id", b"session_id", "text", b"text", "tool_call", b"tool_call"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_content: _TypeAlias = _typing.Literal["text", "tool_call", "error"]  # noqa: Y015
    _WhichOneofArgType_content: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_content) -> _WhichOneofReturnType_content | None: ...

Global___ServerMessage: _TypeAlias = ServerMessage  # noqa: Y015

@_typing.final
class ToolCall(_message.Message):
    """Tool 调用请求（Python → Java）"""

    DESCRIPTOR: _descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: _builtins.int
    TOOL_NAME_FIELD_NUMBER: _builtins.int
    ARGUMENTS_FIELD_NUMBER: _builtins.int
    call_id: _builtins.str
    """调用 ID，用于关联结果"""
    tool_name: _builtins.str
    """工具名：search_shop / query_voucher_of_shop / create_blog"""
    arguments: _builtins.str
    """JSON 参数字符串"""
    def __init__(
        self,
        *,
        call_id: _builtins.str = ...,
        tool_name: _builtins.str = ...,
        arguments: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arguments", b"arguments", "call_id", b"call_id", "tool_name", b"tool_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ToolCall: _TypeAlias = ToolCall  # noqa: Y015

@_typing.final
class ToolResult(_message.Message):
    """Tool 执行结果回传（Java → Python）"""

    DESCRIPTOR: _descriptor.Descriptor

    CALL_ID_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    call_id: _builtins.str
    """对应 ToolCall.call_id"""
    result: _builtins.str
    """JSON 结果字符串"""
    def __init__(
        self,
        *,
        call_id: _builtins.str = ...,
        result: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["call_id", b"call_id", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ToolResult: _TypeAlias = ToolResult  # noqa: Y015

@_typing.final
class Error(_message.Message):
    """错误信息"""

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    message: _builtins.str
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Error: _TypeAlias = Error  # noqa: Y015
